 
# GPIO  
SERVO_PIN = 6            
ULTRASONIC_TRIGGER = 15  
ULTRASONIC_ECHO = 4      
IR_SENSOR_PIN = 22      #  slot đỗ
LED_PIN = 13             
BUTTON_PIN = 21          

 
TOTAL_SLOTS = 5          
SERVO_OPEN_ANGLE = 90    
SERVO_CLOSE_ANGLE = 0    
DISTANCE_THRESHOLD = 20  
DEBOUNCE_TIME = 0.3      
